import type { Metadata } from "next";
import { Newsreader, Instrument_Sans } from "next/font/google";
import "./globals.css";
import { site } from "@/lib/site";
// Statically imported for the same reason Hero.tsx imports its plate that way:
// the emitted URL carries a content hash. A fixed /images/… path would let every
// social platform that has already cached the card keep serving the old one after
// a re-run of scripts/og-card.mjs. The import also supplies the dimensions, so
// they cannot drift from the file.
import ogCard from "@/public/images/og-card.png";
import Nav from "@/components/layout/Nav";
import Footer from "@/components/layout/Footer";
import SiteChrome from "@/components/layout/SiteChrome";
import SmoothScroll from "@/components/motion/SmoothScroll";
import GrainBackground from "@/components/motion/GrainBackground";
import FilmGrade from "@/components/brand/FilmGrade";

// Headline typeface. Variable, with the optical-size axis loaded so large
// display settings get the tighter, higher-contrast cut (font-optical-sizing
// is set on headings in globals.css).
const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  axes: ["opsz"],
  display: "swap",
});

// Everything functional: body copy, buttons, nav, eyebrows, labels. Loaded as a
// variable font rather than a fixed weight list — the type system uses 400
// (body), 500 (nav, eyebrows) and 600 (buttons), and one variable file covers
// the range for less than three static cuts would cost.
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  display: "swap",
});

/**
 * The share card, generated by scripts/og-card.mjs — regenerate it there rather
 * than editing artwork by hand.
 *
 * Declared once and given to both openGraph and twitter. Twitter does fall back to
 * og:image when twitter:image is absent, but `summary_large_image` reserves the
 * space either way, so the card is named explicitly rather than left to a fallback.
 *
 * One card serves the whole site: /careers and the legal routes set only title,
 * description and alternates, so they inherit this openGraph object whole — which
 * also means they inherit its title. Per-page cards would need each route to
 * declare its own openGraph block.
 */
const shareImage = {
  url: ogCard.src,
  width: ogCard.width,
  height: ogCard.height,
  alt: "ATB. — The future, put to work.",
};

export const metadata: Metadata = {
  metadataBase: new URL(site.domain),
  title: {
    default: "ATB. AI-native products for the customer frontline",
    template: "%s · ATB.",
  },
  description: site.description,
  applicationName: "ATB.",
  keywords: [
    "AI-native products",
    "customer frontline AI",
    "FrontlineOS",
    "CommerceOS",
    "MarketingOS",
    "AI product studio",
    "forward-deployed AI",
  ],
  authors: [{ name: site.fullName }],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: site.domain,
    siteName: site.name,
    title: "ATB. AI-native products for the customer frontline",
    description: site.description,
    images: [shareImage],
  },
  twitter: {
    card: "summary_large_image",
    title: "ATB. AI-native products for the customer frontline",
    description: site.description,
    images: [shareImage],
  },
  robots: { index: true, follow: true },
};

const orgJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: site.fullName,
  alternateName: "ATB.",
  legalName: site.legalName,
  url: site.domain,
  email: site.email,
  description: site.description,
  slogan: site.tagline,
  foundingDate: "2025",
  sameAs: [site.social.linkedin, site.social.x],
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: site.name,
  url: site.domain,
  publisher: { "@type": "Organization", name: site.fullName },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${newsreader.variable} ${instrumentSans.variable}`}
    >
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        {/* SiteChrome keeps the marketing furniture off /design — see the note
            in the component. The film-grade defs stay unconditional: they are
            filter definitions with no visual output of their own. */}
        <SiteChrome>
          <SmoothScroll />
          <GrainBackground />
        </SiteChrome>
        {/* Filter defs only — no visual output. Must be in the document for
            `.grade-film`'s `filter: url(#film-grade)` to resolve. */}
        <FilmGrade />
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[110] focus:rounded-full focus:bg-[color:var(--color-copper)] focus:px-5 focus:py-2 focus:text-[color:var(--color-ink)]"
        >
          Skip to content
        </a>
        <SiteChrome>
          <Nav />
        </SiteChrome>
        <main id="main" className="relative">
          {children}
        </main>
        <SiteChrome>
          <Footer />
        </SiteChrome>
      </body>
    </html>
  );
}
